### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by marmuzevichv** [marmuzevichv/insta-s-vyebonamy#5]
gradle-resources-test:Instagramm.test: java.lang.NoClassDefFoundError: org/apache/tools/ant/util/ReaderInputStream
i see that error even when i come back to my previous commit, what did you do ? WTF

**Comment by ekurdesov** [comment]
I suggest you make a new project. your java files will be the same but you will learn something again. Maybe the Gradle trigger for your cucumber got messed up. 
 
 Create a new project and do it over again, you will learn better this way
